### ISSUE TITLE
Can't get out of inline code

### ISSUE THREAD

**Issue by igraziatto** [vanilla/rich-editor#102] opened 2018-08-06 13:46 UTC
**Steps to reproduce:**

- Write something else and then your code inline.
- select your code and change the style to "code".
- Try to get out of the "code" style (I this case I tried with "space", "enter", "esc"...nothing works)
The only thing that worked was to hit enter and select "paragraph" styles again. (not very accessible)

Btw, earlier today I selected the "code" style by mistake and wanted to unselect but it doesn't unselect if you click again on the same option. idk if this is a behaviour it wasn't implemented on purpose but I find myself doing that a lot whenever I want to unselect something.

**Comment by charrondev** [comment] 2018-08-06 14:44
Closing as a duplicate of https://github.com/vanilla/rich-editor/issues/18

**Closed by charrondev** 2018-08-06 14:44 UTC
